# Generated by Django 5.1.2 on 2024-11-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=0, null=0),
        ),
    ]
