# Generated by Django 5.1.2 on 2024-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', null=0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', null=0),
        ),
    ]
