# Generated by Django 5.1.2 on 2025-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=1, default='bg.jpg', max_length=50, null=1),
        ),
    ]
